#!/bin/bash
set -e

# This script performs the complete automated setup based on a single
# config file, by calling the `host/setup_btrfs.sh`, `host/setup_host.sh`,
# `host/setup_network.sh` scripts with that single file.

# First and only argument is the combined config file to be used
CONFIG_FILE="${1}"

# config file needs to exist
if [ ! -f "${CONFIG_FILE}" ]; then
	echo "Must specify "
fi

# Load the config file
. "${CONFIG_FILE}"


# The setup is split into two stages, the optional btrfs stage, and the
# required host setup and network stage.
# The btrfs setup needs to be run before the other scripts and reboot because
# it changes the default subvol and grub configuration.
# The host and network setup always requires a reboot because it changes
# the grub and network configuration.
# So the second stage is run after a reboot if btrfs is enabled,
# or immediately if not.
cat << EOF > /setup_second_stage
#!/bin/bash
set -e
# This file is automatically generated and should delete itself
# automatically as well.

# also save a log output to a logfile
exec >  >(tee -ia /second_stage_setup.log)
exec 2> >(tee -ia /second_stage_setup.log >&2)

# enter the directory we're currently in during setup
cd "${PWD}"

# forward the CONFIG_FILE variable from the setup_all.sh script
CONFIG_FILE="${CONFIG_FILE}"

# Perform second-stage host setup:
echo "Second Stage setup using configuration: \${CONFIG_FILE}"
./host/setup_host.sh "\${CONFIG_FILE}"
./host/setup_network.sh "\${CONFIG_FILE}"

# remove from runlevel
systemctl disable setup_second_stage

# remove second-stage script
rm \${0}

# reload systemd config
systemctl daemon-reload

# Also used to detect the completed setup in remote_install
# DO NOT CHANGE.
echo "*** SECOND STAGE SETUP COMPLETED ***"

# reboot system
reboot

EOF

# script needs to be executable
chmod u+x /setup_second_stage

cat << EOF > /etc/systemd/system/setup_second_stage.service
[Unit]
Description=Run second stage installation once

[Service]
Type=oneshot
ExecStart=/setup_second_stage

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable setup_second_stage


# first setup step needs to be btrfs, if enabled
if [ "${ENABLE_BTRFS}" = true ]; then
	# btrfs setup is enabled, run the setup
	./host/setup_btrfs.sh "{$CONFIG_FILE}"
	# We need to reboot here, because we're on an old subvol
	reboot
else
	/setup_second_stage
fi
